### PR TITLE
Adds support for relative path inside the container

### PR DESCRIPTION
**Pull request by max107**
Adds support for relative path inside the container

```
sudo docker run -i -v /my_super_app/releases:/releases -e SLUG_URL=/releases/2013-11-30_21-10-52.tgz -p 127.0.0.1::5000 -d flynn/slugrunner start web
```

### CODE REVIEW

**Comment by dangra** [comment]
:+1:

**Comment by progrium** [comment]
Did you try a SLUG_URL of file:///releases/2013-11-30_21-10-52.tgz? Pretty sure that should work. If so, maybe you can contribute an example in the docs.

**Comment by max107** [comment]
@progrium Unfortunately, this construction doesn't work for me, maybe i did something wrong. I'll try again, thanks for information. However, pull request doesn't break backward compatibility. I think it should be added to main code.

Unfortunately, I can't update documentation, my English is pretty bad

**Comment by progrium** [comment]
I just don't want to add unnecessary code. curl supports file: so it seems
like this should be the way to go. I also don't want to support two
different APIs because I wouldn't want to call this SLUG_URL, it's really
SLUG_PATH.

On Tue, Dec 3, 2013 at 5:00 AM, Maxim notifications@github.com wrote:

> @progrium https://github.com/progrium Unfortunately, this construction
> doesn't work for me, maybe i did something wrong. I'll try again, thanks
> for information. However, pull request doesn't break backward
> compatibility. I think it should be added to main code.
> 
> Unfortunately, I can't update documentation, my English is pretty bad
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/flynn/slugrunner/pull/2#issuecomment-29707448
> .

## 

Jeff Lindsay
http://progrium.com

**Comment by max107** [comment]
Hmm.. ok.

**Pull request closed without merging**
