### PR TITLE
Add Flynn DATABASE_URL support via sdutil expose

### PR DESCRIPTION
**Pull request by titanous**
@miracle2k @progrium This works, but feels pretty ugly. Any comments/suggestions?

### CODE REVIEW

**Comment by progrium** [comment]
Oof. Hardcoded backing service / addon support (though I know DB is most common) ... I guess I can't think of the right solution but my suggestion as a step in the right direction is to ask how would you generalize this?

**Comment by miracle2k** [comment]
sdutil is ugly to use in general. Using it with a regular docker image usually means creating a descendant image, adding the binary, messing with the cmd/entrypoints of the image, hardcoding the required services, uploading it to the index etc. 

[It makes me wonder if the process shouldn't happen outside the container, i.e. flynn-host or docker itself (there is also npm:docker-discover using docker events, though it does only registration, not consumption). See also https://github.com/flynn/sdutil/issues/1.]

**Comment by progrium** [comment]
That's how I'm starting to think about it as well.

On Sun, Apr 27, 2014 at 6:31 PM, Michael Elsdörfer <notifications@github.com

> wrote:
> 
> sdutil is ugly to use in general. Using it with a regular docker image
> usually means creating a descendant image, adding the binary, messing with
> the cmd/entrypoints of the image, hardcoding the required services,
> uploading it to the index etc.
> 
> [It makes me wonder if the process shouldn't happen outside the container,
> i.e. flynn-host or docker itself (there is also npm:docker-discover using
> docker events, though it does only registration, not consumption). See also
> flynn/sdutil#1 https://github.com/flynn/sdutil/issues/1]
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/flynn/slugrunner/pull/11#issuecomment-41514680
> .

## 

Jeff Lindsay
http://progrium.com

**Comment by titanous** [comment]
Yep, was thinking about this today too.

**Comment by miracle2k** [comment]
The knowledge of which services are required belongs to whom? flynn-controller, right? You'd add service dependencies to your app in the same way as you define environment variables?

So then either let the controller construct the right cmd/entrypoint to call sdutil with the right service queries.

Or the service dependencies need to be passed to slugrunner via some defined protocol. This would be a protocol of flynn-controller's choosing that slugrunner elects to speak. I like this one better.

Maybe this protocol could be added to sdutil directly. I certainly can see it being useful to define dependencies for non-slugrunner containers.

In https://github.com/flynn/sdutil/issues/5 we talked about generating config files. It wouldn't be a stretch to construct environment variables using such a functionality. The `bash -c` can get messy real quick. Does this patch work, for example, if the password were to contain a quote?

**Comment by titanous** [comment]
A quick thought: discoverd is part of layer 0, so it's totally fine if flynn-host talks to discoverd about jobs it is running.

**Comment by progrium** [comment]
Yeah, I think flynn-host needs to take more responsibility for brokering
service awareness. I have some ideas I'll be prototyping soon, but up for
anything in the meantime.

On Sun, Apr 27, 2014 at 6:37 PM, Jonathan Rudenberg <
notifications@github.com> wrote:

> A quick thought: discoverd is part of layer 0, so it's totally fine if
> flynn-host talks to discoverd about jobs it is running.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/flynn/slugrunner/pull/11#issuecomment-41514853
> .

## 

Jeff Lindsay
http://progrium.com

**Comment by miracle2k** [comment]
I have not looked at layer 1, but am I correct that the service dependencies would be part of the "application definition" as given to flynn-controller?

**Comment by progrium** [comment]
So generally yes. In layer 1, application dependencies look slightly more
like Heroku addons, but that's just some metadata and hooks around the
lower level concept of service discovery in layer 0.

On Mon, Apr 28, 2014 at 9:08 AM, Michael Elsdörfer <notifications@github.com

> wrote:
> 
> I have not looked at layer 1, but am I correct that the service
> dependencies would be part of the "application definition" as given to
> flynn-controller?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/flynn/slugrunner/pull/11#issuecomment-41569708
> .

## 

Jeff Lindsay
http://progrium.com

**Comment by titanous** [comment]
Yeah, we expect flynn-controller to be aware of all of the dependencies that an "application" needs. This allows us to tell layer 0 how to hook up service discovery really easily. It also means we get precise network ACLs and capability-based authorization with very little configuration.

**Pull request closed without merging**
